"""Modelos SQLAlchemy. Importar aqui garante o registro no metadata do Alembic."""

from app.models.ai import (
    AICacheEntry,
    AIFeature,
    AIFeatureBinding,
    AIModel,
    AIProviderConfig,
    AIProviderSlug,
    AIUsage,
)
from app.models.audit import AuditLog, ConsentLog
from app.models.board_knowledge import (
    BoardKnowledgeEntry,
    BoardKnowledgeKind,
    KnowledgeSource,
)
from app.models.catalog import (
    Competition,
    CompetitionStatus,
    EducationLevel,
    ExamBoard,
    GovernmentSphere,
    Organization,
    Position,
    PositionSubject,
    Subject,
    Topic,
)
from app.models.document import (
    Document,
    DocumentChunk,
    DocumentKind,
    DocumentStatus,
    ExtractionMethod,
)
from app.models.intelligence import (
    AnalysisSource,
    BoardProfileMetric,
    ErrorAnalysis,
    ErrorCause,
    TopicIncidence,
    TrapPattern,
    UserPriority,
)
from app.models.notice import Notice, NoticeFile, NoticeFileStatus, NoticeKind, NoticeStatus
from app.models.notice_analysis import (
    EvidenceLevel,
    NoticeEvent,
    NoticeEventKind,
    NoticeFact,
    NoticeSection,
    NoticeSectionKind,
    NoticeSubject,
    NoticeTopic,
)
from app.models.question import (
    Alternative,
    Exam,
    Question,
    QuestionAttempt,
    QuestionDifficulty,
    QuestionKind,
    QuestionOrigin,
    QuestionStats,
    QuestionStatus,
    Simulation,
    SimulationAttempt,
    SimulationAttemptStatus,
    SimulationKind,
    SimulationQuestion,
)
from app.models.rbac import Permission, Role, role_permissions, user_roles
from app.models.study import (
    StudyAvailability,
    StudyPeriod,
    StudyPlan,
    StudyPlanStatus,
    StudySession,
    StudySessionStatus,
    StudyTask,
    StudyTaskKind,
    StudyTaskSource,
    StudyTaskStatus,
    UserSubjectProgress,
)
from app.models.token import AuthToken, AuthTokenType
from app.models.tutor import (
    ChatMode,
    Conversation,
    Message,
    MessageRole,
    VideoResource,
    VocabularyTerm,
)
from app.models.user import Profile, User, UserStatus
from app.models.user_session import UserSession

__all__ = [
    "AICacheEntry",
    "AIFeature",
    "AIFeatureBinding",
    "AIModel",
    "AIProviderConfig",
    "AIProviderSlug",
    "AIUsage",
    "Alternative",
    "AnalysisSource",
    "AuditLog",
    "AuthToken",
    "AuthTokenType",
    "BoardKnowledgeEntry",
    "BoardKnowledgeKind",
    "BoardProfileMetric",
    "ChatMode",
    "Competition",
    "CompetitionStatus",
    "ConsentLog",
    "Conversation",
    "Document",
    "DocumentChunk",
    "DocumentKind",
    "DocumentStatus",
    "EducationLevel",
    "ErrorAnalysis",
    "ErrorCause",
    "EvidenceLevel",
    "Exam",
    "ExamBoard",
    "ExtractionMethod",
    "GovernmentSphere",
    "KnowledgeSource",
    "Message",
    "MessageRole",
    "Notice",
    "NoticeEvent",
    "NoticeEventKind",
    "NoticeFact",
    "NoticeFile",
    "NoticeFileStatus",
    "NoticeKind",
    "NoticeSection",
    "NoticeSectionKind",
    "NoticeStatus",
    "NoticeSubject",
    "NoticeTopic",
    "Organization",
    "Permission",
    "Position",
    "PositionSubject",
    "Profile",
    "Question",
    "QuestionAttempt",
    "QuestionDifficulty",
    "QuestionKind",
    "QuestionOrigin",
    "QuestionStats",
    "QuestionStatus",
    "Role",
    "Simulation",
    "SimulationAttempt",
    "SimulationAttemptStatus",
    "SimulationKind",
    "SimulationQuestion",
    "StudyAvailability",
    "StudyPeriod",
    "StudyPlan",
    "StudyPlanStatus",
    "StudySession",
    "StudySessionStatus",
    "StudyTask",
    "StudyTaskKind",
    "StudyTaskSource",
    "StudyTaskStatus",
    "Subject",
    "Topic",
    "TopicIncidence",
    "TrapPattern",
    "User",
    "UserPriority",
    "UserSession",
    "UserStatus",
    "UserSubjectProgress",
    "VideoResource",
    "VocabularyTerm",
    "role_permissions",
    "user_roles",
]
