"""Ajusta uma migração recém-gerada às convenções do projeto.

O autogenerate do Alembic não conhece nossas escolhas: PK portável entre MySQL e
SQLite, opções de tabela do MySQL, índices fora de ``batch_alter_table`` (que no
MySQL recriaria a tabela à toa) e o ``CURRENT_TIMESTAMP`` sem parênteses.

Uso: ``python scripts/normalize_migration.py alembic/versions/<arquivo>.py``
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

HEADER = """branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# SQLite (usado nos testes) só auto-incrementa colunas INTEGER.
BIGINT_PK = sa.BigInteger().with_variant(sa.Integer(), "sqlite")

# Opções aplicadas somente no MySQL; ignoradas pelos demais dialetos.
MYSQL_OPTS = {
    "mysql_engine": "InnoDB",
    "mysql_charset": "utf8mb4",
    "mysql_collate": "utf8mb4_0900_ai_ci",
}
"""

_BATCH_INDEX_BLOCK = re.compile(
    r"    with op\.batch_alter_table\('[^']+', schema=None\) as batch_op:\n"
    r"(?:        batch_op\.(?:create|drop)_index\(.+\n)+"
)


def unbatch_indexes(block: str) -> str:
    table_match = re.search(r"batch_alter_table\('([^']+)'", block)
    assert table_match is not None
    table = table_match.group(1)

    lines: list[str] = []
    for line in block.splitlines():
        stripped = line.strip()
        create = re.match(r"batch_op\.create_index\((.+)\)$", stripped)
        drop = re.match(r"batch_op\.drop_index\((.+)\)$", stripped)
        if create:
            args = create.group(1).replace("batch_op.f(", "op.f(")
            # create_index recebe a tabela como segundo posicional.
            name, rest = args.split(", ", 1)
            lines.append(f'    op.create_index({name}, "{table}", {rest})')
        elif drop:
            args = drop.group(1).replace("batch_op.f(", "op.f(")
            lines.append(f'    op.drop_index({args}, table_name="{table}")')
    return "\n".join(lines) + "\n"


def normalize(source: str) -> str:
    source = source.replace(
        """import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql
revision""",
        """import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

revision""",
    )
    source = source.replace(
        """import sqlalchemy as sa
from alembic import op
revision""",
        """import sqlalchemy as sa

from alembic import op

revision""",
    )
    source = re.sub(r"revision: str = '([^']+)'", r'revision: str = "\1"', source)
    source = re.sub(
        r"down_revision: str \| None = '([^']+)'",
        r'down_revision: str | None = "\1"',
        source,
    )

    anchor = (
        "branch_labels: str | Sequence[str] | None = None\n"
        "depends_on: str | Sequence[str] | None = None\n"
    )
    if "BIGINT_PK" not in source:
        source = source.replace(anchor, HEADER)
    source = source.replace(
        "sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True",
        "BIGINT_PK, autoincrement=True",
    )
    source = source.replace("sa.text('(CURRENT_TIMESTAMP)')", 'sa.text("CURRENT_TIMESTAMP")')

    source = _BATCH_INDEX_BLOCK.sub(lambda match: unbatch_indexes(match.group(0)), source)

    # MYSQL_OPTS entra ao final de cada create_table. O autogenerate escreve o
    # nome da tabela na mesma linha da chamada; o ruff format quebra em duas.
    def _with_opts(match: re.Match[str]) -> str:
        body, closing = match.group(1), match.group(2)
        # Sem a vírgula final, "**MYSQL_OPTS" seria lido como potência do último
        # argumento em vez de desempacotamento — o autogenerate nem sempre a põe.
        if not body.rstrip().endswith(","):
            body = body.rstrip() + ",\n"
        return body + "    **MYSQL_OPTS,\n" + closing

    source = re.sub(
        r"(op\.create_table\((?:.|\n)*?\n)(    \)\n)",
        _with_opts,
        source,
    )

    source = source.replace(
        "    # ### commands auto generated by Alembic - please adjust! ###\n", ""
    )
    source = source.replace("    # ### end Alembic commands ###\n", "")
    return source


def main() -> int:
    if len(sys.argv) != 2:
        print(__doc__, file=sys.stderr)
        return 2
    path = Path(sys.argv[1])
    path.write_text(normalize(path.read_text()))
    print(f"normalizada: {path.name}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
