"""Mestre Game Engine — regras puras, sem I/O e sem IA."""

from app.domain.game.achievements import (
    ACHIEVEMENTS,
    ACHIEVEMENTS_BY_SLUG,
    AchievementCategory,
    AchievementEvaluation,
    AchievementProgress,
    AchievementSpec,
    evaluate,
)
from app.domain.game.levels import (
    MAX_LEVEL,
    LevelProgress,
    cumulative_xp,
    level_for_xp,
    xp_for_level,
)
from app.domain.game.missions import (
    MAX_DAILY_MISSIONS,
    MissionBlueprint,
    MissionKind,
    MissionPriority,
    MissionSignals,
    daily_bonus_xp,
    generate_daily,
)
from app.domain.game.ranks import (
    TIERS,
    RankComponent,
    RankInput,
    RankResult,
    RankTier,
    compute_rank,
    tier_for,
)
from app.domain.game.streak import (
    SHIELDS_PER_MONTH,
    DayRecord,
    StreakState,
    build_streak,
    qualifies,
)
from app.domain.game.xp import (
    DEFAULT_RULES,
    RULES_BY_KEY,
    GameEvent,
    GameEventKind,
    XPAward,
    XPRule,
    score_event,
    valid_questions,
)

__all__ = [
    "ACHIEVEMENTS",
    "ACHIEVEMENTS_BY_SLUG",
    "DEFAULT_RULES",
    "MAX_DAILY_MISSIONS",
    "MAX_LEVEL",
    "RULES_BY_KEY",
    "SHIELDS_PER_MONTH",
    "TIERS",
    "AchievementCategory",
    "AchievementEvaluation",
    "AchievementProgress",
    "AchievementSpec",
    "DayRecord",
    "GameEvent",
    "GameEventKind",
    "LevelProgress",
    "MissionBlueprint",
    "MissionKind",
    "MissionPriority",
    "MissionSignals",
    "RankComponent",
    "RankInput",
    "RankResult",
    "RankTier",
    "StreakState",
    "XPAward",
    "XPRule",
    "build_streak",
    "compute_rank",
    "cumulative_xp",
    "daily_bonus_xp",
    "evaluate",
    "generate_daily",
    "level_for_xp",
    "qualifies",
    "score_event",
    "tier_for",
    "valid_questions",
    "xp_for_level",
]
